site_name: FastDocs
site_url: https://doc.fastx-ai.com
site_description: FastDoc is a website that you can get started with FastX AI in minutes.
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.indexes
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - navigation.prune
    - content.action.edit
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - announce.dismiss
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow
    - toc.integrate
  icon:
    logo: material/library
    repo: fontawesome/brands/github-alt
    edit: material/pencil-box
    view: material/eye
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - search
  - blog:
      blog_toc: true
      pagination_per_page: 10
      archive_pagination_per_page: 10
      categories_pagination_per_page: 10
  - tags:
      tags_file: tags.md
  - rss:
      match_path: "blog/posts/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
      categories:
        - categories
        - tags
      comments_path: "#__comments"
  - social:
      cards_layout_options:
        background_color: "#4051b5"
        font_family: Noto Sans SC
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: C-L-STARK/C-L-STARK.github.io
      branch: master
  - git-authors
  - glightbox
nav:
  - 主页: index.md
  - 后端: backend/index.md
  - 前端: web/index.md
  - 客户端: client/index.md
  - 桌面端: pc/index.md
  - 大数据: big-data/index.md
  - 人工智能: 
      - ml/1_58_llm_extreme_quantization.md
      - ml/2023-in-llms.md
      - ml/3d-assets.md
      - ml/4bit-transformers-bitsandbytes.md
      - ml/Llama2-for-non-engineers.md
      - ml/Lora-for-sequence-classification-with-Roberta-Llama-Mistral.md
      - ml/_policy-ntia-rfc.md
      - ml/accelerate-v1.md
      - ml/accelerated-inference.md
      - ml/agents.md
      - ml/aivsai.md
      - ml/arena-tts.md
      - ml/asr-diarization.md
      - ml/assisted-generation-support-gaudi.md
      - ml/assisted-generation.md
      - ml/audioldm2.md
      - ml/autoformer.md
      - ml/beating-gaia.md
      - ml/big-bird.md
      - ml/blip-2.md
      - ml/bloom-inference-optimization.md
      - ml/bloom-inference-pytorch-scripts.md
      - ml/bloom-megatron-deepspeed.md
      - ml/bridgetower.md
      - ml/chat-templates.md
      - ml/chinese-ai-expansion.md
      - ml/chinese-language-blog.md
      - ml/cloudflare-workers-ai.md
      - ml/codellama.md
      - ml/community-datasets.md
      - ml/constrained-beam-search.md
      - ml/controlnet.md
      - ml/cosmopedia.md
      - ml/cost-efficient-rag-applications-with-intel.md
      - ml/cv_state.md
      - ml/daily-papers.md
      - ml/dedup.md
      - ml/deep-learning-with-proteins.md
      - ml/deepspeed-to-fsdp-and-back.md
      - ml/deploy-deepfloydif-using-bentoml.md
      - ml/deploy-with-openvino.md
      - ml/dialog-agents.md
      - ml/diffusers-turns-1.md
      - ml/docmatix.md
      - ml/document-ai.md
      - ml/dpo-trl.md
      - ml/dpo_vlm.md
      - ml/dreambooth.md
      - ml/dynamic_speculation_lookahead.md
      - ml/elixir-bumblebee.md
      - ml/embedding-quantization.md
      - ml/encoder-decoder.md
      - ml/encrypted-llm.md
      - ml/ethics-diffusers.md
      - ml/ethics-soc-3.md
      - ml/ethics-soc-4.md
      - ml/falcon-180b.md
      - ml/falcon.md
      - ml/falconmamba.md
      - ml/fine-tune-whisper.md
      - ml/fine-video.md
      - ml/finetune-florence2.md
      - ml/game-jam-first-edition-results.md
      - ml/gaussian-splatting.md
      - ml/gemma-july-update.md
      - ml/gemma-peft.md
      - ml/gemma.md
      - ml/gemma2.md
      - ml/generative-ai-models-on-intel-cpu.md
      - ml/getting-started-habana.md
      - ml/google-cloud-model-garden.md
      - ml/gptq-integration.md
      - ml/gradio-5.md
      - ml/gradio-lite.md
      - ml/gradio-reload.md
      - ml/graphml-classification.md
      - ml/habana-gaudi-2-benchmark.md
      - ml/habana-gaudi-2-bloom.md
      - ml/hf-bitsandbytes-integration.md
      - ml/how-to-generate.md
      - ml/hugging-face-wiz-security-blog.md
      - ml/huggy-lingo.md
      - ml/idefics.md
      - ml/idefics2.md
      - ml/if.md
      - ml/image-similarity.md
      - ml/inference-endpoints-llm.md
      - ml/inference-update.md
      - ml/infini-attention.md
      - ml/informer.md
      - ml/instruction-tuning-sd.md
      - ml/intel-fast-embedding.md
      - ml/intel-protein-language-model-protst.md
      - ml/intel-sapphire-rapids-inference.md
      - ml/intel-sapphire-rapids.md
      - ml/intel-starcoder-quantization.md
      - ml/intro-graphml.md
      - ml/introducing-csearch.md
      - ml/introduction-to-ggml.md
      - ml/jat.md
      - ml/kv-cache-quantization.md
      - ml/langchain.md
      - ml/large-language-models.md
      - ml/lcm_lora.md
      - ml/leaderboard-bigcodebench.md
      - ml/leaderboard-decodingtrust.md
      - ml/leaderboard-medicalllm.md
      - ml/leaderboard-patronus.md
      - ml/llama2.md
      - ml/llama3.md
      - ml/llama31.md
      - ml/llama32.md
      - ml/long-range-transformers.md
      - ml/lora.md
      - ml/mask2former.md
      - ml/matryoshka.md
      - ml/megatron-training.md
      - ml/mixtral.md
      - ml/ml-for-games-1.md
      - ml/ml-for-games-2.md
      - ml/ml-for-games-3.md
      - ml/ml-for-games-4.md
      - ml/ml-for-games-5.md
      - ml/mms_adapters.md
      - ml/moe.md
      - ml/multi-lora-serving.md
      - ml/noob_intro_transformers.md
      - ml/open-llm-leaderboard-drop.md
      - ml/open-llm-leaderboard-mmlu.md
      - ml/open-llm-leaderboard-rlhf.md
      - ml/open-source-llms-as-agents.md
      - ml/optimize-llm.md
      - ml/optimizing-bark.md
      - ml/optimum-onnxruntime-training.md
      - ml/os-llms.md
      - ml/overview-quantization-transformers.md
      - ml/packing-with-FA2.md
      - ml/paligemma.md
      - ml/password-git-deprecation.md
      - ml/peft.md
      - ml/personal-copilot.md
      - ml/phi2-intel-meteor-lake.md
      - ml/presidio-pii-detection.md
      - ml/putting_rl_back_in_rlhf_with_rloo.md
      - ml/pycharm-integration.md
      - ml/pytorch-ddp-accelerate-transformers.md
      - ml/pytorch-fsdp.md
      - ml/quanto-diffusers.md
      - ml/quanto-introduction.md
      - ml/ram-efficient-pytorch-fsdp.md
      - ml/red-teaming.md
      - ml/reformer.md
      - ml/regions.md
      - ml/researcher-dataset-sharing.md
      - ml/rlhf.md
      - ml/rwkv.md
      - ml/ryght-case-study.md
      - ml/safecoder.md
      - ml/sc2-instruct.md
      - ml/sd3-5.md
      - ml/sd3.md
      - ml/sd_distillation.md
      - ml/sdxl_lora_advanced_script.md
      - ml/setfit-absa.md
      - ml/setfit-optimum-intel.md
      - ml/setfit.md
      - ml/smollm.md
      - ml/speecht5.md
      - ml/sql-console.md
      - ml/stable-diffusion-finetuning-intel.md
      - ml/stable-diffusion-inference-intel.md
      - ml/stable_diffusion.md
      - ml/stackllama.md
      - ml/starchat-alpha.md
      - ml/starcoder.md
      - ml/starcoder2.md
      - ml/synthetic-data-save-costs.md
      - ml/synthid-text.md
      - ml/t2i-sdxl-adapters.md
      - ml/text-to-video.md
      - ml/textgen-pipe-gaudi.md
      - ml/tgi-benchmarking.md
      - ml/the-age-of-ml-as-code.md
      - ml/the_n_implementation_details_of_rlhf_with_ppo.md
      - ml/time-series-transformers.md
      - ml/train-dgx-cloud.md
      - ml/train-optimize-sd-intel.md
      - ml/train-sentence-transformers.md
      - ml/train-your-controlnet.md
      - ml/transformers-design-philosophy.md
      - ml/trl-ddpo.md
      - ml/trl-peft.md
      - ml/trufflesecurity-partnership.md
      - ml/unified-tool-use.md
      - ml/unity-api.md
      - ml/unity-asr.md
      - ml/unity-in-spaces.md
      - ml/universal_assisted_generation.md
      - ml/vertex-colored-to-textured-mesh.md
      - ml/vision_language_pretraining.md
      - ml/vit-align.md
      - ml/vlms.md
      - ml/watermarking.md
      - ml/whisper-speculative-decoding.md
      - ml/winning-aimo-progress-prize.md
      - ml/xethub-joins-hf.md
      - ml/zero-shot-vqa-docmatix.md
  - 运维: ops/index.md
  - 博客:
      - blog/index.md
  - 简历模板: resume/index.html
extra:
  social:
    - icon: fontawesome/brands/mastodon
      name: fastx-ai
      link: https://fastx-ai.com
    - icon: /fontawesome/regular/envelope
      name: send me an email
      link: mailto:x.stark.dylan@gmail.com
    - icon: /material/mailbox
      name: contact us
      link: /contact
  analytics: 
    provider: google
    property: G-XXXXXXXXXX
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
hooks:
  - hooks/socialmedia.py
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
repo_url: https://github.com/C-L-STARK/C-L-STARK.github.io
repo_name: C-L-STARK/C-L-STARK.github.io
edit_uri: edit/master/docs/
copyright: Copyright &copy; 2020 - 2024 FastX-AI
