site_name: FastDocs
site_url: https://doc.fastx-ai.com
site_description: FastDoc is a website that you can get started with FastX AI in minutes.
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.indexes
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - navigation.prune
    - content.action.edit
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - announce.dismiss
    - search.suggest
    - search.highlight
    - search.share
    - toc.follow
    - toc.integrate
  icon:
    logo: material/library
    repo: fontawesome/brands/github-alt
    edit: material/pencil-box
    view: material/eye
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
plugins:
  - search
  - blog:
      blog_toc: true
      pagination_per_page: 10
      archive_pagination_per_page: 10
      categories_pagination_per_page: 10
  - tags:
      tags_file: tags.md
  - rss:
      match_path: "blog/posts/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
      categories:
        - categories
        - tags
      comments_path: "#__comments"
  - social:
      cards_layout_options:
        background_color: "#4051b5"
        font_family: Noto Sans SC
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: C-L-STARK/C-L-STARK.github.io
      branch: master
  - git-authors
  - glightbox
nav:
  - Home: index.md
  - Install: install.md
  - Usage: usage.md
  - Blog:
      - blog/index.md
  - Tags: tags.md
  # - Resume: resume/index.html
extra:
  social:
    - icon: fontawesome/brands/mastodon
      name: fastx-ai
      link: https://fastx-ai.com
    - icon: /fontawesome/regular/envelope
      name: send me an email
      link: mailto:x.stark.dylan@gmail.com
    - icon: /material/mailbox
      name: contact us
      link: /contact
  alternate:
    - name: English
      link: /
      lang: en
    - name: 简体中文
      link: /zh/
      lang: zh
  analytics: 
    provider: google
    property: G-XXXXXXXXXX
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
hooks:
  - hooks/socialmedia.py
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
repo_url: https://github.com/C-L-STARK/C-L-STARK.github.io
repo_name: C-L-STARK/C-L-STARK.github.io
edit_uri: edit/master/docs/
copyright: Copyright &copy; 2020 - 2024 FastX-AI
